# Checkov configuration for Algalon Terraform security scanning
# Documentation: https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

# Directories to scan
directory:
  - terraform/

# Output format
output: 
  - cli
  - sarif

# Create baseline (skip existing issues)
create-baseline: false

# Download external modules for scanning
download-external-modules: true

# Framework to scan
framework:
  - terraform

# Skip checks that are not applicable to our use case
skip-check:
  # VM disks for critical VMs must be encrypted but we use default encryption
  - CKV_GCP_37  # Ensure VM disks for critical VMs are encrypted with Customer Supplied Encryption Keys (CSEK)
  - CKV_GCP_38  # Ensure VM disks for critical VMs are encrypted with Customer Supplied Encryption Keys (CSEK)

  # Shielded VM is not supported on all machine types
  - CKV_GCP_39  # Ensure Compute instances are launched with shielded VM enabled

  # Some instances need public IPs for specific use cases
  - CKV_GCP_40  # Ensure that Compute instances do not have public IP addresses

# Checks to enforce (high priority security)
check:
  - CKV_GCP_1   # Ensure that Google Cloud Resource Manager service has been secured
  - CKV_GCP_2   # Ensure GCP compute firewall ingress does not allow unrestricted access on port 22
  - CKV_GCP_3   # Ensure GCP compute firewall ingress does not allow unrestricted access on port 3389
  - CKV_GCP_4   # Ensure no HTTPS or SSL proxy load balancers permit SSL policies with weak cipher suites
  - CKV_GCP_26  # Ensure that VPC Flow Logs is enabled for every subnet in a VPC Network
  - CKV_GCP_27  # Ensure that the default network does not exist in a project
  - CKV_GCP_28  # Ensure that Cloud Storage bucket is not anonymously or publicly accessible
  - CKV_GCP_29  # Ensure that Cloud Storage bucket is not anonymously or publicly accessible
  - CKV_GCP_30  # Ensure that instances are not configured to use the default service account
  - CKV_GCP_31  # Ensure that instances are not configured to use the default service account with full access to all Cloud APIs
  - CKV_GCP_32  # Ensure 'Block Project-wide SSH keys' is enabled for VM instances
  - CKV_GCP_33  # Ensure oslogin is enabled for a Project
  - CKV_GCP_34  # Ensure that no instance in the project overrides the project setting for enabling OSLogin(OSLogin needs to be enabled in project metadata for all instances)
  - CKV_GCP_35  # Ensure ‘Enable connecting to serial ports’ is not enabled for VM Instance
  - CKV_GCP_36  # Ensure that IP forwarding is not enabled on Instances
  - CKV_GCP_41  # Ensure that IAM users are not assigned the Service Account User or Service Account Token Creator roles at project level
  - CKV_GCP_42  # Ensure that Service Account has no Admin privileges
  - CKV_GCP_44  # Ensure no roles that enable to impersonate and manage all service accounts are used at a folder level
  - CKV_GCP_45  # Ensure no roles that enable to impersonate and manage all service accounts are used at an organization level
  - CKV_GCP_46  # Ensure Default Service account is not used at a project level
  - CKV_GCP_47  # Ensure default service account is not used at an organization level
  - CKV_GCP_48  # Ensure roles do not impersonate or manage Service Accounts used at project level
  - CKV_GCP_88  # Ensure Google compute firewall ingress does not allow unrestricted mysql access
  - CKV_GCP_106 # Ensure Google compute firewall ingress does not allow unrestricted http port 80 access
  - CKV_GCP_107 # Cloud functions should not be public



# External checks directory (if any custom checks)
external-checks-dir: []

# Quiet mode (reduce output verbosity)
quiet: false

# Compact mode (reduce output verbosity but show results)
compact: true

# Create a JUnit XML report
output-file-path: reports/

# Baseline file to compare against
baseline: null

# CA certificate bundle file
ca-certificate: null

# Repository root for relative paths
# repo-root-for-plan-enrichment:

# External modules directory
# external-modules-download-path:

# Evaluate variables
evaluate-variables: true
