services:
  all-smi:
    image: ghcr.io/inureyes/all-smi:latest
    container_name: algalon-all-smi
    ports:
      - "9400:9400"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    cap_add:
      - SYS_ADMIN
    command: ["api", "--port", "9400", "--interval", "5", "--processes"]
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
