services:
  all-smi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: algalon-all-smi
    ports:
      - "${ALL_SMI_PORT:-9090}:${ALL_SMI_PORT:-9090}"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    cap_add:
      - SYS_ADMIN
    command: ["api", "--port", "${ALL_SMI_PORT:-9090}", "--interval", "${ALL_SMI_INTERVAL:-5}", "--processes"]
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
